var num1 = [];
var num2 = [];
var num3 = new Array();
num1.push(10);
num1.push(20);
num1.push(30);
var names = new Array();
var info1 = new Array();
info1.push(100);
info1.push("ravi");
info1.push(true);
var emp1 = { id: 100, name: "ravi", age: 21 };
var emp2 = { id: 101, name: "radha", age: 20 };
var emp3 = { id: 102, name: "rash", age: 31 };
var emp4 = { id: 103, name: "lokesh", age: 36 };
var emp5 = { id: 104, name: "mahesh", age: 24 };
var employees = new Array();
employees.push(emp1);
employees.push(emp2);
employees.push(emp3);
employees.push(emp4);
employees.push(emp5);
employees.forEach(function (e) { return console.log(e.id + " " + e.name + " " + e.age); });
